#!/usr/bin/env python3

import sys
from core.printf import *
from core.parguments import *
from core.handleProcess import *

def main():
	parser,args = PArguments.Main_Arguments()

	if args.target == False:
		if args.help == False:
			sys.exit(UsageMain())
		else:
			sys.exit(parser.print_help())

	else:
		process = getProcess(args)
		if len(process()) == 0:
			if args.help == False:
				sys.exit(UsageMain())
			else:
				sys.exit(parser.print_help())
		else:
			for _ in process():
				Handle(_,args)


if __name__ == '__main__':
	main()